# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfacelogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowLogin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginUsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginUsernameLabel.setGeometry(QtCore.QRect(120, 60, 61, 16))
        self.loginUsernameLabel.setObjectName("loginUsernameLabel")
        self.loginUsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.loginUsernameInput.setGeometry(QtCore.QRect(250, 60, 113, 20))
        self.loginUsernameInput.setObjectName("loginUsernameInput")
        self.loginPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginPasswordLabel.setGeometry(QtCore.QRect(120, 140, 61, 21))
        self.loginPasswordLabel.setObjectName("loginPasswordLabel")
        self.loginPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.loginPasswordInput.setGeometry(QtCore.QRect(240, 140, 113, 20))
        self.loginPasswordInput.setObjectName("loginPasswordInput")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(210, 220, 75, 23))
        self.loginButton.setObjectName("loginButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginUsernameLabel.setText(_translate("MainWindow", "Username"))
        self.loginPasswordLabel.setText(_translate("MainWindow", "Password"))
        self.loginButton.setText(_translate("MainWindow", "Login"))

